### PR TITLE
Improve Binder

### LINKED ISSUE #2: Binder fails at postBuild step
I've noticed that binder seems to always fail at the postBuild step after it has built the conda environment, and downloaded and extracted all of the data. I'm not really sure what's going wrong here.
[hcg_hi_analysis_binder_build.log](https://github.com/AMIGA-IAA/hcg_global_hi_analysis/files/9996252/hcg_hi_analysis_binder_build.log)

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**
This is an attempt to improve mybinder deployment and fix: https://github.com/AMIGA-IAA/hcg_global_hi_analysis/issues/2

xrefs:
* https://github.com/AMIGA-IAA/hcg-16/pull/14
* https://conda-incubator.github.io/conda-lock/

However, I am still getting the same error:
```
Error removing intermediate container 94c744059fac: No such container: 94c744059faceee7c5bbba589dd4536af8bd040ba183be78fba10186f70a8a93
unknown parent image ID sha256:adef09a9712d9c35c587a139adf4f40e3616fa05f41cdb668d7276cf5b360158
```

mybinder URL to test this branch:
https://mybinder.org/v2/gh/AMIGA-IAA/hcg_global_hi_analysis/binder

Reporting and waiting for guidance in:
https://discourse.jupyter.org/t/unknown-parent-image-id/

### CODE REVIEW

**Comment by sebastian-luna-valero** [comment]
Hi,

@jonesmg would you be able to try the following:

1. Go to binder: https://mybinder.org/v2/gh/AMIGA-IAA/hcg_global_hi_analysis/binder
2. Open a terminal in JupyterLab and run the `postBuild` commands below manually:

```bash
# download data
zenodo_get -r 6366659

#unzip HCG_VLA_HI_data_products.zip
unzip GBT_spectra.zip
unzip optical_images.zip
unzip HCG_VLA_HI_mom1_maps.zip
```

Does this work properly?

Thanks,
Sebastian

**Comment by jonesmg** [comment]
Hi Sebastian,

This very nearly works. It successfully launched the jupyter session and after downloading and extracting the files I could run some of the notebooks. However, it seems that the pycf3 dependency in the environment file never got installed. This was trivial to install with `pip install pycf3==2020.12` within the jupyter terminal, and then almost everything worked properly. For some reason the make_spectra notebook kernel dies at the same point every time I run it. I've run this notebook on another machine with no problems, so I wonder if somehow I'm hitting the limit of the resources allocated.

Cheers,

Mike

**Comment by sebastian-luna-valero** [comment]
Thanks for the tests, Mike.

I am asking about the missing pip dependencies here: https://github.com/conda-incubator/conda-lock/issues/285

After that, I will look into the issue with `make_spectra` notebook.

**Comment by jonesmg** [comment]
Thanks Sebastian. Just note that you need to run the `make_HCG_table` notebook prior to the `make_spectra` one.

**Comment by sebastian-luna-valero** [comment]
Hi Mike,

I was able to kill the `kernel` with `make_spectra` as well. It also seems to me that we are hitting the limits on mybinder. Is it with the cell below as well for you?

imagen

Is there a way to optimize this notebook? or should we discard binder?

After discussing in https://discourse.jupyter.org/t/unknown-parent-image-id/ I believe the best option is to move the below to the notebooks (maybe `make_HCG_table`?):
```bash
# download data
zenodo_get -r 6366659

unzip HCG_VLA_HI_data_products.zip
unzip GBT_spectra.zip
unzip optical_images.zip
unzip HCG_VLA_HI_mom1_maps.zip
```

Adding `pycf3` to the [start](https://github.com/AMIGA-IAA/hcg_global_hi_analysis/blob/binder/binder/start) file seems to solve the problem with this `pip` dependency. However, going back to the original `environment.yml` (i.e. removing the `conda-lock`) would also be a (slower) solution which would be consisten with the manual workflow in the `README`.

Please let me know your thoughts.

Best regards,
Sebastian

**Comment by jonesmg** [comment]
Hi Sebastian,

I think I would prefer to have something equivalent to the postBuild script, but just indicate in the instructions that this needs to be executed manually after the Jupyter session launches. The reason is that the Zenodo repo also includes all the data tables (although this archive is left untouched by default), which means that someone may want to just use the pre-made data tables and not run any of the initial notebooks, instead skipping straight to the final notebooks.

The make_spectra notebook kernel died at the same place for me. I've investigated this a bit further and I think the `plt.savefig` commands are causing a memory leak. The problem is not specific to HCG22. This happens sooner or later regardless of what order the plots are made in. I've been trying every solution that I've found online to clear/close the plots after they are saved, but nothing seems to be working. I'll tackle it some more another day.

Thanks,

Mike

**Comment by sebastian-luna-valero** [comment]
Thanks Mike,

From my side, this PR now contains all the changes required to fix the launch on mybinder with all the required dependencies (including `pip`).

Remaining actions:
1. Update the docs to include the download of data from zenodo (as it was in the postBuild)
1. Investigate whether the issues with `make_spectra` notebook can be solved.

I could help with 1 but not with 2. Not sure whether @jmoldon can help here.

Please confirm if you want me to do action 1.

Best regards,
Sebastian

**Comment by jmoldon** [comment]
An easy way to facilitate the garbage collector to reduce the memory footprint is to include the calculations inside a function that is called in an outer loop. That way all the fits are used and should be automatically deleted before processing another source. So just as simple as this:

```python
def plot_spectra(HCG):
    mask = 'SoFiA_masks/HCG{0}/HCG{0}_mask.fits'.format(HCG)
    pbcube = 'SoFiA_masks/HCG{0}/HCG{0}_HI.pbcor.fits'.format(HCG)
    flatcube = 'SoFiA_masks/HCG{0}/HCG{0}_HI.fits'.format(HCG)
    src_cat = 'SoFiA_masks/HCG{0}/HCG{0}_cat.xml'.format(HCG)
    
    print("HCG{}:".format(HCG))
...
...

for HCG in VLA_HCGs:
    plot_spectra(HCG)
```
maybe it needs additional variables to be parsed to the function.

The round and write functions where you see it failing shouldn't be too problematic, and I would expect it to fail before, during the loop. Anyways, it is worth trying the function in a loop.

**Comment by jonesmg** [comment]
Hi Sebastian and Javier,

Sebastian, yes it would be great if you can update the docs to indicate what steps now need to be run manually. Probably just in the "Launching through binder" section. 

Javier, I did try putting all the the plotting within a function, but I was quite surprised that this didn't solve the issue. I will try this again and keep tweaking it to identify the exact issue. However, I agree with Sebastian that the main purpose of this PR was to fix the issue with binder not launching, so when that's finished I'll merge with master and then go from there. (Unless I solve the notebook issue before Sebastian updates the docs.)

Cheers,

Mike

**Comment by sebastian-luna-valero** [comment]
Hi,

Here is my proposal: https://github.com/AMIGA-IAA/hcg_global_hi_analysis/pull/3/commits/42815a85748897794bc5a8c9f3c82a787feeb11d

Best regards,
Sebastian

**Pull request merged**
